version: "3.7"
services:
  app:
    build:
      args:
        user: mac
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: portallist
    container_name: portallist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - portallist

  db:
    image: mysql:8.0
    container_name: portallist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - portallist

  nginx:
    image: nginx:alpine
    container_name: portallist-nginx
    restart: unless-stopped
    ports:
      - 14050:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - portallist
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portallist-phpmyadmin
    ports:
     - 14051:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
    restart: always
    networks:
      - portallist

networks:
  portallist:
    driver: bridge
